# Generated by Django 2.1.3 on 2018-12-09 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id_card', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_card', models.CharField(max_length=20)),
                ('due_card', models.DateTimeField()),
                ('color_card', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='constructor_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graber.Constructor'),
        ),
        migrations.AddField(
            model_name='card',
            name='list_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graber.List'),
        ),
    ]
